[package]
name = "merkle"
version = "0.2.0"
authors = ["ChainX <https://github.com/chainx-org>"]
edition = "2018"
license = "GPL-3.0"

[features]
default = []
std = [
  "primitives/std",
  "serialization/std",
  "chain/std",
  "codec/std",
]

[dependencies]
primitives = { path = "../primitives", default-features = false }
serialization = { path = "../serialization", default-features = false, features = ["derive"] }
chain = { path = "../chain", default-features = false }
codec = { package = "parity-scale-codec", version = "1.3", default-features = false }

[dev-dependencies]
crypto = { path = "../crypto", default-features = false }
hashbrown = { version = "0.7", default-features = false, features = ["ahash"] }
hex = { version = "0.4", default-features = false }
rand = "0.7"
