[package]
name = "primitives"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com> and koushiro <koushiro.cqx@gmail.com>"]
edition = "2018"

[dependencies]
ustd = { git = "https://github.com/chainx-org/chainx-common", default-features = false }
byteorder = { version = "1.3", default-features = false }
rustc-hex = { version = "2.0", default-features = false }
fixed-hash = { version = "0.3", default-features = false }
primitive-types = { version = "0.2", default-features = false, features = ["codec"] }

[features]
default = ["std"]
std = [
    "ustd/std",
    "byteorder/std",
    "rustc-hex/std",
    "fixed-hash/std",
    "primitive-types/std",
]
impl-rustc-hex = ["primitive-types/rustc-hex", "fixed-hash/rustc-hex"]
impl-serde = ["std", "primitive-types/serde"]
impl-rlp = ["std", "primitive-types/rlp"]
