[package]
name = "primitives"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com> and koushiro <koushiro.cqx@gmail.com>"]
edition = "2018"

[dependencies]
ustd = { git = "https://github.com/chainx-org/chainx-common", default-features = false }
primitive-types = { git = "https://github.com/chainx-org/chainx-common", default-features = false, features = ["codec"] }
byteorder = { version = "1.3", default-features = false }
rustc-hex = { version = "2.0", default-features = false }

serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }

[features]
default = ["std"]
std = [
    "ustd/std",
    "byteorder/std",
    "rustc-hex/std",
    "primitive-types/std",
    "primitive-types/serde",

    "serde",
    "serde_derive",
]
