[package]
name = "light-bitcoin"
version = "0.1.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io> and koushiro <koushiro.cqx@gmail.com>"]
description = "A light bitcoin library that supports `no_std`."
edition = "2018"

[dependencies]
rstd = { path = "rstd" }
primitives = { path = "primitives" }
bitcrypto = { path = "crypto" }
base58 = { path = "base58" }
keys = { path = "keys" }
#chain = { path = "chain" }
#script = { path = "script" }
serialization = { path = "serialization" }
serialization_derive = { path = "serialization_derive" }

[workspace]
members = [
    "rstd",
    "primitives",
    "crypto",
    "base58",
    "keys",
#    "chain",
#    "script",
    "serialization",
    "serialization_derive"
]
