[package]
name = "light-bitcoin-wasm-test"
version = "0.1.0"
authors = ["ChainX <https://github.com/chainx-org>"]
edition = "2018"

[features]
std = ["light-bitcoin/std"]

[dependencies]
wee_alloc = "0.4.5"
light-bitcoin = { path = "../", default-features = false }
