version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:16.04

    working_directory: ~/light-bitcoin-ci

    steps:
      - checkout

      - run:
          name: Setting up build environment
          command: |
            apt-get update
            apt-get install -y curl build-essential zlib1g-dev
            curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path --default-toolchain nightly-2019-03-05 -y;
            source $HOME/.cargo/env
            rustup component add rustfmt
            rustup component add clippy
          no_output_timeout: 1800s

      - run:
          name: Checking format
          command: |
            export PATH=~/.cargo/bin:$PATH
            cargo fmt -- --check

      - run:
          name: Lint
          command: |
            export PATH=~/.cargo/bin:$PATH
            cargo clippy -- -Dwarnings

      - run:
          name: Test
          command: |
            export PATH=~/.cargo/bin:$PATH
            export RUST_BACKTRACE=1
            cargo test

workflows:
  version: 2.1
  build:
    jobs:
      - build
