version: 2.1
jobs:
  build:
    machine: true

    working_directory: ~/light-bitcoin

    steps:
      - checkout
      - run:
          name: Setup build environment
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake binutils-dev libcurl4-openssl-dev libiberty-dev libelf-dev libdw-dev
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path --default-toolchain none -y;
          no_output_timeout: 1800s
      - run:
          name: Format
          command: |
            export PATH=~/.cargo/bin:$PATH
            rustup component add rustfmt
            cargo fmt --all -- --check
      - run:
          name: Clippy
          command: |
            export PATH=~/.cargo/bin:$PATH
            rustup component add clippy
            cargo clippy --all -- -D warnings
      - run:
          name: Test
          command: |
            export PATH=~/.cargo/bin:$PATH
            export RUST_BACKTRACE=1

            # test std
            cargo test --all --exclude serialization_derive
            cd serialization_derive && cargo test --test raw && cd ..

            # test no_std
            cd primitives && cargo test --no-default-features --features codec && cd ..
            cd serialization && cargo test --no-default-features && cd ..
            cd crypto && cargo test --no-default-features && cd ..
            cd keys && cargo test --no-default-features && cd ..
            cd chain && cargo test --no-default-features && cd ..
            cd script && cargo test --no-default-features && cd ..
            cd merkle && cargo test --no-default-features && cd ..

      - run:
          name: Coverage
          command: |
            export PATH=~/.cargo/bin:$PATH
            # install kcov
            cargo install cargo-kcov
            cargo kcov --print-install-kcov-sh | sh
            echo "Install kcov successfully"
            # coverage
            cargo kcov --all -v
            bash <(curl -s https://codecov.io/bash)
            echo "Upload code coverage successfully"

workflows:
  version: 2.1
  build:
    jobs:
      - build
