[package]
name = "serialization"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com> and koushiro <koushiro.cqx@gmail.com>"]
edition = "2018"

[dependencies]
primitives = { path = "../primitives", default-features = false }

[features]
default = ["std"]
std = ["primitives/std"]
