[package]
name = "chain"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com> and koushiro <koushiro.cqx@gmail.com>"]
edition = "2018"

[dependencies]
ustd = { git = "https://github.com/chainx-org/chainx-common", default-features = false }
primitives = { path = "../primitives", default-features = false }
crypto = { path = "../crypto", default-features = false }
serialization = { path = "../serialization", default-features = false }
rustc-hex = { version = "2.0", default-features = false }

[features]
default = ["std"]
std = [
    "ustd/std",
    "primitives/std",
    "crypto/std",
    "serialization/std",
    "rustc-hex/std",
]
