[package]
name = "chain"
version = "0.2.0"
authors = ["ChainX <https://github.com/chainx-org>"]
edition = "2018"
license = "GPL-3.0"

[features]
default = []
std = [
  "primitives/std",
  "serialization/std",
  "crypto/std",

  "rustc-hex/std",
  "codec/std",
  "serde/std",
]

[dependencies]
primitives = { path = "../primitives", default-features = false }
serialization = { path = "../serialization", default-features = false, features = ["derive"] }
crypto = { path = "../crypto", default-features = false }

rustc-hex = { version = "2.0", default-features = false }
codec = { package = "parity-scale-codec", version = "1.3", default-features = false, features = ["derive"] }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "merkle_root"
path = "benches/merkle_root.rs"
harness = false
