[package]
name = "chain"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com> and koushiro <koushiro.cqx@gmail.com>"]
edition = "2018"

[dependencies]
primitives = { path = "../primitives", default-features = false, features = ["codec"] }
serialization = { path = "../serialization", default-features = false }
crypto = { path = "../crypto", default-features = false }

rustc-hex = { version = "2.0", default-features = false }
parity-codec = { version = "3.5", default-features = false, features = ["derive"] }
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = ["std"]
std = [
    "primitives/std",
    "serialization/std",
    "crypto/std",
    "rustc-hex/std",

    "parity-codec/std",
    "serde",
]
