[package]
name = "keys"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com> and koushiro <koushiro.cqx@gmail.com>"]
edition = "2018"

[dependencies]
ustd = { git = "https://github.com/chainx-org/chainx-common", default-features = false }
base58 = { git = "https://github.com/chainx-org/chainx-common", default-features = false }
primitives = { path = "../primitives", default-features = false }
serialization = { path = "../serialization", default-features = false }
crypto = { path = "../crypto", default-features = false }

rustc-hex = { version = "2.0", default-features = false }
libsecp256k1 = "0.2.2"  # support `no_std`

parity-codec = { version = "3.2", default-features = false }
parity-codec-derive = { version = "3.1", default-features = false }
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }

[features]
default = ["std"]
std = [
    "ustd/std",
    "base58/std",
    "primitives/std",
    "serialization/std",
    "crypto/std",
    "rustc-hex/std",

    "parity-codec/std",
    "parity-codec-derive/std",
    "serde",
    "serde_derive",
]
