[package]
name = "keys"
version = "0.2.0"
authors = ["ChainX <https://github.com/chainx-org>"]
edition = "2018"
license = "GPL-3.0"

[features]
default = []
std = [
  "primitives/std",
  "serialization/std",
  "crypto/std",
  "rustc-hex/std",
  "libsecp256k1/std",
  "codec/std",
  "serde/std",
]

[dependencies]
primitives = { path = "../primitives", default-features = false }
serialization = { path = "../serialization", default-features = false, features = ["derive"] }
crypto = { path = "../crypto", default-features = false }
bs58 = { version = "0.3", default-features = false, features = ["alloc"] }
rustc-hex = { version = "2.0", default-features = false }
libsecp256k1 = { version = "0.3.5", default-features = false, features = ["hmac"] }
codec = { package = "parity-scale-codec", version = "1.3",  default-features = false, features = ["derive"] }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }

[dev-dependencies]
hex-literal = "0.2"
