[package]
name = "keys"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com> and koushiro <koushiro.cqx@gmail.com>"]
edition = "2018"

[dependencies]
rstd = { path = "../rstd", default-features = false }
primitives = { path = "../primitives", default-features = false }
bitcrypto = { path = "../crypto", default-features = false }
base58 = { path = "../base58", default-features = false }
rustc-hex = { version = "2", default-features = false }
libsecp256k1 = "0.2.2"  # support `no_std`

[features]
default = ["std"]
std = [
    "rstd/std",
    "primitives/std",
    "bitcrypto/std",
    "base58/std",
    "rustc-hex/std"
]
