[package]
name = "keys"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com> and koushiro <koushiro.cqx@gmail.com>"]
edition = "2018"

[dependencies]
primitives = { path = "../primitives", default-features = false, features = ["codec"] }
serialization = { path = "../serialization", default-features = false, features = ["derive"] }
crypto = { path = "../crypto", default-features = false }
bs58 = { version = "0.3", default-features = false, features = ["alloc"] }
rustc-hex = { version = "2.0", default-features = false }
libsecp256k1 = "0.3.1"  # support `no_std` by default
codec = { package = "parity-codec", version = "3.5",  default-features = false, features = ["derive"] }
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
hex-literal = "0.2"

[features]
default = ["std"]
std = [
    "primitives/std",
    "serialization/std",
    "crypto/std",
    "rustc-hex/std",
    "codec/std",
    "serde",
]
