[package]
name = "bitcrypto"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com> and koushiro <koushiro.cqx@gmail.com>"]
edition = "2018"

[dependencies]
rstd = { path = "../rstd" }
primitives = { path = "../primitives" }
rcrypto = { version = "0.2.36", package = "rust-crypto" }
siphasher = "0.1.1"

[features]
default = ["std"]
std = [
    "rstd/std",
    "primitives/std"
]
